import { vanillaExtractPlugin } from '@vanilla-extract/vite-plugin';
import react from '@vitejs/plugin-react';
import { defineConfig, type Plugin } from 'vite';

function typeStub(stylesheet: string): string {
  return `// Generated by vite.config.ts, so \`import '…/${stylesheet}'\` resolves to a
// type instead of failing with TS2882.
export {};
`;
}

/**
 * Vite emits one stylesheet per chunk: `theme.css` (the tokens) and `index.css`
 * (the component rules). `theme.css` ships as it is; `styles.css` is the two
 * concatenated, so it keeps meaning "everything". The component-only half is
 * dropped — component rules without their variables are not a useful import.
 */
function bundleStylesheet(): Plugin {
  const published = ['styles.css', 'theme.css'];

  return {
    name: 'trailpack-bundle-stylesheet',
    generateBundle(_options, bundle) {
      const tokens = bundle['theme.css'];
      const components = bundle['index.css'];

      // A renamed entry would otherwise publish a `styles.css` missing half its
      // rules.
      if (
        tokens?.type !== 'asset' ||
        components?.type !== 'asset' ||
        typeof tokens.source !== 'string' ||
        typeof components.source !== 'string'
      ) {
        throw new Error(
          'Expected Vite to emit theme.css and index.css as text assets. ' +
            `Got: ${Object.keys(bundle).join(', ')}`,
        );
      }

      this.emitFile({
        type: 'asset',
        fileName: 'styles.css',
        source: `${tokens.source}${components.source}`,
      });

      delete bundle['index.css'];

      for (const stylesheet of published) {
        this.emitFile({
          type: 'asset',
          fileName: `${stylesheet}.d.ts`,
          source: typeStub(stylesheet),
        });
      }
    },
  };
}

export default defineConfig({
  plugins: [react(), vanillaExtractPlugin(), bundleStylesheet()],
  build: {
    cssCodeSplit: true,
    sourcemap: true,
    lib: {
      entry: {
        index: 'src/index.ts',
        'theme/index': 'src/theme/index.ts',
      },
      formats: ['es'],
    },
    rollupOptions: {
      // `@vanilla-extract/recipes` stays external: its runtime is tiny, but the
      // emitted .d.ts reference its types, so consumers need it resolvable
      // anyway. Bundling it would ship the same code twice.
      external: [/^react($|\/)/, /^react-dom($|\/)/, /^@vanilla-extract\/recipes($|\/)/],
      // Stylesheet names are public API, so nothing here may be hashed.
      output: { assetFileNames: '[name][extname]' },
    },
  },
});
