import { vanillaExtractPlugin } from '@vanilla-extract/vite-plugin';
import react from '@vitejs/plugin-react';
import { defineConfig, type Plugin } from 'vite';

/**
 * A type stub for one of the stylesheet exports, emitted next to the stylesheet
 * it describes.
 *
 * The stylesheets are imported for their side effects only, but TypeScript
 * still needs each subpath to resolve to *something* typed: without this,
 * consumers that do not pull in ambient `*.css` declarations (via `vite/client`
 * or similar) fail with TS2882 on `import '@trailpack/react-ui/styles.css'`.
 *
 * Generated rather than checked in, so the package root stays free of hand-kept
 * declarations for build artefacts, and a new stylesheet entry needs one line
 * below instead of a new file plus a `files` entry in package.json.
 */
function typeStub(stylesheet: string): string {
  return `// Generated by vite.config.ts. Makes the \`${stylesheet}\` export of this
// package resolve to a type, so importing it for its side effects does not
// fail with TS2882 in consumers without ambient \`*.css\` declarations.
export {};
`;
}

/**
 * With `cssCodeSplit` on, Vite emits one stylesheet per chunk: `theme.css` from
 * the `theme/index` entry (the tokens) and `index.css` from `index` (the
 * component rules). `theme.css` ships as it is, for consumers that want the
 * tokens without the components.
 *
 * `styles.css` — the entry the whole library documents — is the two of them
 * concatenated, so it keeps meaning "everything" and stays one request. The
 * component-only half is dropped: component rules without the variables they
 * reference are not a useful thing to import.
 *
 * Every stylesheet that survives this gets its type stub emitted alongside it.
 */
function bundleStylesheet(): Plugin {
  const published = ['styles.css', 'theme.css'];

  return {
    name: 'trailpack-bundle-stylesheet',
    generateBundle(_options, bundle) {
      const tokens = bundle['theme.css'];
      const components = bundle['index.css'];

      // Loud on purpose. These names come from the entry names below, so a
      // renamed entry or a moved import would otherwise publish a `styles.css`
      // that had silently lost half its rules.
      if (
        tokens?.type !== 'asset' ||
        components?.type !== 'asset' ||
        typeof tokens.source !== 'string' ||
        typeof components.source !== 'string'
      ) {
        throw new Error(
          'Expected Vite to emit theme.css and index.css as text assets. ' +
            `Got: ${Object.keys(bundle).join(', ')}`,
        );
      }

      // Tokens first: the component rules reference the variables they declare.
      this.emitFile({
        type: 'asset',
        fileName: 'styles.css',
        source: `${tokens.source}${components.source}`,
      });

      delete bundle['index.css'];

      for (const stylesheet of published) {
        this.emitFile({
          type: 'asset',
          fileName: `${stylesheet}.d.ts`,
          source: typeStub(stylesheet),
        });
      }
    },
  };
}

export default defineConfig({
  plugins: [react(), vanillaExtractPlugin(), bundleStylesheet()],
  build: {
    // On, so the tokens can be published without the component rules. The two
    // halves are recombined into `styles.css` by the plugin above.
    cssCodeSplit: true,
    sourcemap: true,
    lib: {
      entry: {
        index: 'src/index.ts',
        'theme/index': 'src/theme/index.ts',
      },
      formats: ['es'],
    },
    rollupOptions: {
      // `@vanilla-extract/recipes` stays external: its runtime is tiny, but the
      // emitted .d.ts reference its types, so consumers need it resolvable
      // anyway. Bundling it would ship the same code twice.
      external: [/^react($|\/)/, /^react-dom($|\/)/, /^@vanilla-extract\/recipes($|\/)/],
      output: {
        // Stylesheets are named after their chunk (`theme.css`, `index.css`);
        // both are part of the public API, so nothing here may be hashed.
        assetFileNames: '[name][extname]',
      },
    },
  },
});
